Update `./release`

diff --git a/release b/release
--- a/release
+++ b/release
@@ -90,13 +90,23 @@ case "$sub" in
 			echo "Working directory is not clean."
 			exit 1
 		fi
+		tag=""
 		(
 			cd "$root/$pkg"
 			tag=$(npm version "$sub" --tag-version-prefix="$pkg@" --message "$pkg@%s")
-			git -C "$root" add "$pkg/package.json" "$pkg/package-lock.json"
-			git -C "$root" commit -m "$tag"
-			git -C "$root" tag "$tag" -m "$tag"
 		)
+		if [ -z "$tag" ]; then
+			echo "Failed to create new version for '$pkg'"
+			exit 1
+		fi
+		last_tag="$(git -C "$root" tag --list "$pkg@*" --sort=-v:refname | head -n 1)"
+		git -C "$root" add "$pkg/package.json" "$pkg/package-lock.json"
+		git -C "$root" commit -m "$tag"
+		git -C "$root" tag "$tag" -m "$tag"
+		echo "+ $tag"
+		if [ -n "$last_tag" ]; then
+			git -C "$root" log "$last_tag..$tag" --format=%B -- "$pkg" | sed '/^$/d'
+		fi
 		;;
 	"history")
 		pkg="${2:?Package name required}"
